package main

import (
	"fmt"
	"sort"
	"strings"
)

// sampleKey indexes a single benchmark cell for O(1) headline lookups.
type sampleKey struct {
	pkg, impl, op string
	size          int
}

func indexSamples(samples []Sample) map[sampleKey]Sample {
	idx := make(map[sampleKey]Sample, len(samples))
	for _, s := range samples {
		idx[sampleKey{s.Pkg, s.Impl, s.Op, s.Size}] = s
	}
	return idx
}

// headlineRow is a resolved headline (label + metrics) ready to render.
type headlineRow struct {
	Label    string
	NsOp     float64
	BytesOp  float64
	AllocsOp float64
}

// resolveHeadlines maps the static allowlist onto the data, dropping (and
// returning) any entries that weren't benchmarked so the preview never shows
// blank rows.
func resolveHeadlines(idx map[sampleKey]Sample) (rows []headlineRow, missing []string) {
	for _, h := range headlines {
		s, ok := idx[sampleKey{h.Pkg, h.Impl, h.Op, h.Size}]
		if !ok {
			missing = append(missing, h.Label)
			continue
		}
		rows = append(rows, headlineRow{h.Label, s.NsOp, s.BytesOp, s.AllocsOp})
	}
	return rows, missing
}

// provenanceCaveat is the shared "indicative, not authoritative" disclaimer,
// consistent with the existing benchstat PR-comment wording.
const provenanceCaveat = "> ⚠️ GitHub-hosted runners are shared and noisy, so these numbers are " +
	"**indicative, not authoritative**. Trust them for orders of magnitude and " +
	"relative comparisons between implementations — not as precise absolute timings."

func orUnknown(s string) string {
	if s == "" {
		return "unknown"
	}
	return s
}

func flagsLine(prov Provenance) string {
	parts := []string{}
	if prov.Benchtime != "" {
		parts = append(parts, "-benchtime="+prov.Benchtime)
	}
	if prov.Count != "" {
		parts = append(parts, "-count="+prov.Count)
	}
	parts = append(parts, "-benchmem")
	return strings.Join(parts, " ")
}

func runner(prov Provenance) string {
	return orUnknown(prov.GOOS) + "/" + orUnknown(prov.GOARCH)
}

// RenderReport produces the full BENCHMARKS.md: provenance header, the curated
// headline table + chart, then the full per-package/per-operation matrix.
func RenderReport(samples []Sample, prov Provenance, svgPath string) string {
	var b strings.Builder
	b.WriteString("# Benchmark report\n\n")
	b.WriteString("<!-- Generated by tools/benchreport — do not edit by hand. Regenerate with `make bench-report`. -->\n\n")
	b.WriteString("This report is regenerated and committed on every push to `main`. " +
		"It is the full companion to the headline preview in the [README](README.md#performance).\n\n")

	b.WriteString("## Provenance\n\n")
	b.WriteString(fmt.Sprintf("- **Commit:** `%s`\n", orUnknown(prov.Commit)))
	b.WriteString(fmt.Sprintf("- **Generated (UTC):** %s\n", orUnknown(prov.Date)))
	b.WriteString(fmt.Sprintf("- **Go:** %s\n", orUnknown(prov.GoVersion)))
	b.WriteString(fmt.Sprintf("- **Runner:** %s\n", runner(prov)))
	b.WriteString(fmt.Sprintf("- **CPU:** %s\n", orUnknown(prov.CPU)))
	b.WriteString(fmt.Sprintf("- **Flags:** `%s`\n", flagsLine(prov)))
	if len(prov.Packages) > 0 {
		b.WriteString(fmt.Sprintf("- **Packages:** %s\n", strings.Join(prov.Packages, ", ")))
	}
	b.WriteString("\n")
	b.WriteString(provenanceCaveat + "\n\n")

	idx := indexSamples(samples)
	if rows, _ := resolveHeadlines(idx); len(rows) > 0 {
		b.WriteString("## Headlines\n\n")
		b.WriteString(fmt.Sprintf("![Benchmark chart](%s)\n\n", svgPath))
		writeHeadlineTable(&b, rows)
		b.WriteString("\n")
	}

	b.WriteString("## Full results\n\n")
	writeFullTables(&b, samples)

	return b.String()
}

func writeHeadlineTable(b *strings.Builder, rows []headlineRow) {
	b.WriteString("| Operation | ns/op | B/op | allocs/op |\n")
	b.WriteString("|---|--:|--:|--:|\n")
	for _, r := range rows {
		b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
			r.Label, formatNs(r.NsOp), formatCount(r.BytesOp), formatCount(r.AllocsOp)))
	}
}

// writeFullTables emits one section per package and, within it, one table per
// operation with a row for every (implementation, size) cell.
func writeFullTables(b *strings.Builder, samples []Sample) {
	byPkg := map[string][]Sample{}
	for _, s := range samples {
		byPkg[s.Pkg] = append(byPkg[s.Pkg], s)
	}
	pkgs := make([]string, 0, len(byPkg))
	for p := range byPkg {
		pkgs = append(pkgs, p)
	}
	sort.Slice(pkgs, func(i, j int) bool {
		if ri, rj := pkgRank(pkgs[i]), pkgRank(pkgs[j]); ri != rj {
			return ri < rj
		}
		return pkgs[i] < pkgs[j]
	})

	for _, pkg := range pkgs {
		b.WriteString("### " + pkg + "\n\n")

		ops := map[string][]Sample{}
		for _, s := range byPkg[pkg] {
			ops[s.Op] = append(ops[s.Op], s)
		}
		opNames := make([]string, 0, len(ops))
		for op := range ops {
			opNames = append(opNames, op)
		}
		sort.Strings(opNames)

		for _, op := range opNames {
			rows := ops[op]
			sort.Slice(rows, func(i, j int) bool {
				if rows[i].Impl != rows[j].Impl {
					return rows[i].Impl < rows[j].Impl
				}
				return rows[i].Size < rows[j].Size
			})
			b.WriteString("#### " + op + "\n\n")
			b.WriteString("| Implementation | Size | ns/op | B/op | allocs/op |\n")
			b.WriteString("|---|--:|--:|--:|--:|\n")
			for _, s := range rows {
				b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
					s.Impl, formatCount(float64(s.Size)),
					formatNs(s.NsOp), formatCount(s.BytesOp), formatCount(s.AllocsOp)))
			}
			b.WriteString("\n")
		}
	}
}

// RenderReadmeRegion produces the marker-delimited preview block injected into
// the README: a short caveat, the curated headline table, the chart, a
// provenance stamp, and a link to the full report. Idempotent for fixed inputs.
func RenderReadmeRegion(samples []Sample, prov Provenance, svgPath, reportPath string) string {
	idx := indexSamples(samples)
	rows, _ := resolveHeadlines(idx)

	var b strings.Builder
	b.WriteString("<!-- Generated by tools/benchreport — do not edit by hand. Regenerate with `make bench-report`. -->\n\n")
	b.WriteString(fmt.Sprintf("_Indicative numbers from a shared CI runner — see [%s](%s) for the full matrix and caveats._\n\n",
		reportPath, reportPath))
	if len(rows) > 0 {
		writeHeadlineTable(&b, rows)
		b.WriteString("\n")
	}
	b.WriteString(fmt.Sprintf("![Benchmark chart](%s)\n\n", svgPath))
	date := prov.Date
	if len(date) >= 10 {
		date = date[:10] // YYYY-MM-DD
	}
	b.WriteString(fmt.Sprintf("Provenance: `%s` · %s · %s · %s\n\n",
		orUnknown(prov.Commit), orUnknown(date), runner(prov), orUnknown(prov.GoVersion)))
	b.WriteString(fmt.Sprintf("Full report → [%s](%s)\n", reportPath, reportPath))
	return b.String()
}
