package main

import (
	"fmt"
	"sort"
	"strings"
)

// sampleKey indexes a single benchmark cell for O(1) headline lookups.
type sampleKey struct {
	pkg, impl, op string
	size          int
}

func indexSamples(samples []Sample) map[sampleKey]Sample {
	idx := make(map[sampleKey]Sample, len(samples))
	for _, s := range samples {
		idx[sampleKey{s.Pkg, s.Impl, s.Op, s.Size}] = s
	}
	return idx
}

// headlineRow is a resolved headline (label + metrics) ready to render.
type headlineRow struct {
	Label    string
	NsOp     float64
	BytesOp  float64
	AllocsOp float64
}

// resolveHeadlines maps the static allowlist onto one dataset's samples,
// dropping (and returning) any entries that weren't benchmarked so the preview
// never shows blank rows.
func resolveHeadlines(idx map[sampleKey]Sample) (rows []headlineRow, missing []string) {
	for _, h := range headlines {
		s, ok := idx[sampleKey{h.Pkg, h.Impl, h.Op, h.Size}]
		if !ok {
			missing = append(missing, h.Label)
			continue
		}
		rows = append(rows, headlineRow{h.Label, s.NsOp, s.BytesOp, s.AllocsOp})
	}
	return rows, missing
}

// orderDatasets returns datasets with the primary tier first, then by env name,
// so the controlled reference environment always leads the report.
func orderDatasets(datasets []Dataset) []Dataset {
	out := append([]Dataset(nil), datasets...)
	sort.SliceStable(out, func(i, j int) bool {
		pi, pj := out[i].Meta.IsPrimary(), out[j].Meta.IsPrimary()
		if pi != pj {
			return pi // primary sorts first
		}
		return out[i].Meta.Env < out[j].Meta.Env
	})
	return out
}

// primaryDataset returns the dataset that should drive the headline table and
// chart: the primary-tier one if present, else the first after ordering.
func primaryDataset(datasets []Dataset) Dataset {
	ordered := orderDatasets(datasets)
	return ordered[0]
}

func orUnknown(s string) string {
	if s == "" {
		return "unknown"
	}
	return s
}

func flagsLine(m Meta) string {
	parts := []string{}
	if m.Benchtime != "" {
		parts = append(parts, "-benchtime="+m.Benchtime)
	}
	if m.Count != "" {
		parts = append(parts, "-count="+m.Count)
	}
	parts = append(parts, "-benchmem")
	return strings.Join(parts, " ")
}

func runner(m Meta) string {
	return orUnknown(m.GOOS) + "/" + orUnknown(m.GOARCH)
}

func datasetLabel(m Meta) string {
	if m.Label != "" {
		return m.Label
	}
	return orUnknown(m.Env)
}

// RenderReport produces the full BENCHMARKS.md across all environments: an
// environments/provenance section, the curated headline table + chart driven by
// the primary (controlled) environment, then the full per-environment matrix —
// primary first, secondary environments flagged as indicative.
func RenderReport(datasets []Dataset, svgPath string) string {
	ordered := orderDatasets(datasets)
	primary := ordered[0]

	var b strings.Builder
	b.WriteString("# Benchmark report\n\n")
	b.WriteString("<!-- Generated by tools/benchreport — do not edit by hand. Regenerate with `make bench-report`. -->\n\n")
	b.WriteString("This report is the full companion to the headline preview in the " +
		"[README](README.md#performance). It surfaces two environments: a controlled " +
		"**reference** machine (the trustworthy baseline) and the **CI** shared runner " +
		"(indicative). Each is regenerated independently — the reference by a maintainer " +
		"running `make bench-report` locally, the CI numbers on every push to `main`.\n\n")

	b.WriteString("## Environments\n\n")
	for _, d := range ordered {
		writeEnvProvenance(&b, d.Meta)
	}
	b.WriteString("> ⚠️ The **CI** environment is a shared, noisy GitHub-hosted runner, so its " +
		"numbers are **indicative, not authoritative** — trust them for orders of magnitude " +
		"and relative comparisons only. The **reference** environment is a fixed, controlled " +
		"machine and is the baseline the headline table and chart are drawn from.\n\n")

	idx := indexSamples(primary.Samples)
	if rows, _ := resolveHeadlines(idx); len(rows) > 0 {
		fmt.Fprintf(&b, "## Headlines — %s\n\n", datasetLabel(primary.Meta))
		fmt.Fprintf(&b, "![Benchmark chart](%s)\n\n", svgPath)
		writeHeadlineTable(&b, rows)
		b.WriteString("\n")
	}

	for _, d := range ordered {
		title := datasetLabel(d.Meta)
		if !d.Meta.IsPrimary() {
			title += " (indicative)"
		}
		fmt.Fprintf(&b, "## Full results — %s\n\n", title)
		writeFullTables(&b, d.Samples)
	}

	return b.String()
}

// writeEnvProvenance emits one environment's provenance as a labelled bullet
// block.
func writeEnvProvenance(b *strings.Builder, m Meta) {
	tier := "secondary"
	if m.IsPrimary() {
		tier = "primary"
	}
	fmt.Fprintf(b, "### %s (%s)\n\n", datasetLabel(m), tier)
	if m.Machine != "" {
		fmt.Fprintf(b, "- **Machine:** %s\n", m.Machine)
	}
	fmt.Fprintf(b, "- **Commit:** `%s`\n", orUnknown(m.Commit))
	fmt.Fprintf(b, "- **Generated (UTC):** %s\n", orUnknown(m.Date))
	fmt.Fprintf(b, "- **Go:** %s\n", orUnknown(m.GoVersion))
	fmt.Fprintf(b, "- **Runner:** %s\n", runner(m))
	fmt.Fprintf(b, "- **CPU:** %s\n", orUnknown(m.CPU))
	fmt.Fprintf(b, "- **Flags:** `%s`\n", flagsLine(m))
	if len(m.Packages) > 0 {
		fmt.Fprintf(b, "- **Packages:** %s\n", strings.Join(m.Packages, ", "))
	}
	b.WriteString("\n")
}

func writeHeadlineTable(b *strings.Builder, rows []headlineRow) {
	b.WriteString("| Operation | ns/op | B/op | allocs/op |\n")
	b.WriteString("|---|--:|--:|--:|\n")
	for _, r := range rows {
		fmt.Fprintf(b, "| %s | %s | %s | %s |\n",
			r.Label, formatNs(r.NsOp), formatCount(r.BytesOp), formatCount(r.AllocsOp))
	}
}

// writeFullTables emits one section per package and, within it, one table per
// operation with a row for every (implementation, size) cell.
func writeFullTables(b *strings.Builder, samples []Sample) {
	byPkg := map[string][]Sample{}
	for _, s := range samples {
		byPkg[s.Pkg] = append(byPkg[s.Pkg], s)
	}
	pkgs := make([]string, 0, len(byPkg))
	for p := range byPkg {
		pkgs = append(pkgs, p)
	}
	sort.Slice(pkgs, func(i, j int) bool {
		if ri, rj := pkgRank(pkgs[i]), pkgRank(pkgs[j]); ri != rj {
			return ri < rj
		}
		return pkgs[i] < pkgs[j]
	})

	for _, pkg := range pkgs {
		b.WriteString("### " + pkg + "\n\n")

		ops := map[string][]Sample{}
		for _, s := range byPkg[pkg] {
			ops[s.Op] = append(ops[s.Op], s)
		}
		opNames := make([]string, 0, len(ops))
		for op := range ops {
			opNames = append(opNames, op)
		}
		sort.Strings(opNames)

		for _, op := range opNames {
			rows := ops[op]
			sort.Slice(rows, func(i, j int) bool {
				if rows[i].Impl != rows[j].Impl {
					return rows[i].Impl < rows[j].Impl
				}
				return rows[i].Size < rows[j].Size
			})
			b.WriteString("#### " + op + "\n\n")
			b.WriteString("| Implementation | Size | ns/op | B/op | allocs/op |\n")
			b.WriteString("|---|--:|--:|--:|--:|\n")
			for _, s := range rows {
				fmt.Fprintf(b, "| %s | %s | %s | %s | %s |\n",
					s.Impl, formatCount(float64(s.Size)),
					formatNs(s.NsOp), formatCount(s.BytesOp), formatCount(s.AllocsOp))
			}
			b.WriteString("\n")
		}
	}
}

// RenderReadmeRegion produces the marker-delimited preview injected into the
// README: the primary (reference) headline table + chart, a one-line provenance
// stamp per environment, and a link to the full report. Idempotent for fixed
// inputs.
func RenderReadmeRegion(datasets []Dataset, svgPath, reportPath string) string {
	ordered := orderDatasets(datasets)
	primary := ordered[0]
	rows, _ := resolveHeadlines(indexSamples(primary.Samples))

	var b strings.Builder
	b.WriteString("<!-- Generated by tools/benchreport — do not edit by hand. Regenerate with `make bench-report`. -->\n\n")
	fmt.Fprintf(&b, "_Headline numbers are from the controlled **%s** baseline; the shared-runner "+
		"**CI** numbers are indicative only. See [%s](%s) for both full matrices and caveats._\n\n",
		datasetLabel(primary.Meta), reportPath, reportPath)
	if len(rows) > 0 {
		writeHeadlineTable(&b, rows)
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "![Benchmark chart](%s)\n\n", svgPath)

	for _, d := range ordered {
		fmt.Fprintf(&b, "%s: `%s` · %s · %s · Go %s\n\n",
			datasetLabel(d.Meta), orUnknown(d.Meta.Commit), orUnknown(shortDate(d.Meta.Date)),
			runner(d.Meta), orUnknown(d.Meta.GoVersion))
	}
	fmt.Fprintf(&b, "Full report → [%s](%s)\n", reportPath, reportPath)
	return b.String()
}

// shortDate trims an ISO timestamp to YYYY-MM-DD for the compact README stamp.
func shortDate(d string) string {
	if len(d) >= 10 {
		return d[:10]
	}
	return d
}
