package main

import (
	"fmt"
	"strings"
)

// Regression-detection policy (issue #51). GitHub-hosted runners are shared and
// noisy, so a single sample — or a single comparison — is untrustworthy. A
// headline is flagged only when ALL of these hold, keeping the alert report-only
// but credible:
//
//   - the median got slower by more than trendRegressFrac (a meaningful effect,
//     not a fraction of a percent), AND
//   - that slowdown is statistically significant (Mann–Whitney p < trendPValue),
//     so it's unlikely to be noise, AND
//   - it shows up in TWO consecutive comparisons (commit n-2→n-1 and n-1→n), so
//     one unlucky noisy run can't trip the alarm on its own.
const (
	trendRegressFrac = 0.10 // ≥10% slower median to count as a regression
	trendPValue      = 0.05 // significance threshold for the Mann–Whitney test
	trendMaxColumns  = 12   // most-recent commits shown in the trend table
)

// trendAnchor is the GitHub-slugified anchor of the trend section heading below,
// used to deep-link the section from the README and BENCHMARKS.md.
const trendAnchor = "trend-recent-main-commits"

// RenderTrendSection renders the long-term trend block appended to BENCHMARKS.md:
// a per-headline table of median ns/op across the most recent retained commits
// (newest first), the significance-gated regression check, and the manual
// benchstat recipe. Returns "" when there is no history yet, so the report
// cleanly omits the section until the first push populates the store.
func RenderTrendSection(entries []HistoryEntry) string {
	if len(entries) == 0 {
		return ""
	}
	shown := newestFirst(entries)
	if len(shown) > trendMaxColumns {
		shown = shown[:trendMaxColumns]
	}

	var b strings.Builder
	b.WriteString("## Trend (recent `main` commits)\n\n")
	b.WriteString("<!-- Generated by tools/benchreport — do not edit by hand. Regenerate with `make bench-report`. -->\n\n")
	fmt.Fprintf(&b, "Median **ns/op** for the headline operations across the last %d of %d retained `main` "+
		"commit(s), measured on the **CI** runner and newest first. CI runners are shared and noisy, so read "+
		"these for *drift* rather than precise values — the regression check below uses statistical "+
		"significance, not raw deltas.\n\n", len(shown), len(entries))

	writeTrendTable(&b, shown)
	writeTrendLegend(&b, shown)
	b.WriteString(RenderRegressionAlert(entries))
	b.WriteString(trendRecipe)
	return b.String()
}

// newestFirst returns a copy of entries (stored oldest→newest) reversed so the
// most recent commit leads.
func newestFirst(entries []HistoryEntry) []HistoryEntry {
	out := make([]HistoryEntry, len(entries))
	for i := range entries {
		out[i] = entries[len(entries)-1-i]
	}
	return out
}

// writeTrendTable emits the headline-operation × commit grid of median ns/op.
// Cells absent from a snapshot (a benchmark added later) render as "—".
func writeTrendTable(b *strings.Builder, shown []HistoryEntry) {
	b.WriteString("| Operation |")
	for _, e := range shown {
		fmt.Fprintf(b, " %s |", orUnknown(e.Commit))
	}
	b.WriteString("\n|---|")
	for range shown {
		b.WriteString("--:|")
	}
	b.WriteString("\n")

	for _, h := range headlines {
		key := sampleKey{h.Pkg, h.Impl, h.Op, h.Size}
		fmt.Fprintf(b, "| %s |", h.Label)
		for _, e := range shown {
			if s := e.Samples[key]; len(s) > 0 {
				fmt.Fprintf(b, " %s |", formatNs(median(s)))
			} else {
				b.WriteString(" — |")
			}
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

// writeTrendLegend maps each shown commit's short SHA to its date, so the compact
// SHA column headers above stay decodable.
func writeTrendLegend(b *strings.Builder, shown []HistoryEntry) {
	parts := make([]string, len(shown))
	for i, e := range shown {
		parts[i] = fmt.Sprintf("`%s` (%s)", orUnknown(e.Commit), orUnknown(shortDate(e.Stamp)))
	}
	fmt.Fprintf(b, "Commits, newest first: %s\n\n", strings.Join(parts, " · "))
}

// regression is one flagged headline: its label and the slowdown observed in the
// most recent comparison.
type regression struct {
	Label     string
	FromNs    float64
	ToNs      float64
	PercentNs float64
}

// RenderRegressionAlert renders the report-only regression check as a standalone
// markdown block: it is embedded in the trend section AND written to a file the
// CI job appends to its run summary. The verdict requires two consecutive
// significant, above-threshold slowdowns (see the policy constants above).
func RenderRegressionAlert(entries []HistoryEntry) string {
	var b strings.Builder
	b.WriteString("### Regression check (report-only)\n\n")

	if len(entries) < 3 {
		fmt.Fprintf(&b, "_Need at least 3 retained commits to confirm a regression across two consecutive "+
			"comparisons; have %d. Trend will begin flagging once more history accrues._\n\n", len(entries))
		return b.String()
	}

	flagged := detectRegressions(entries)
	if len(flagged) == 0 {
		b.WriteString("✅ No headline operation regressed significantly (Mann–Whitney `p` < 0.05, " +
			"> 10% slower median) across the last two consecutive `main` commits.\n\n")
		return b.String()
	}

	n := len(entries)
	fmt.Fprintf(&b, "⚠️ **%d headline operation(s) regressed** across the last two consecutive commits "+
		"(`%s` → `%s` → `%s`) — each slower by > 10%% with Mann–Whitney `p` < 0.05. Report-only; "+
		"investigate before trusting, since CI runners are noisy.\n\n",
		len(flagged), orUnknown(entries[n-3].Commit), orUnknown(entries[n-2].Commit), orUnknown(entries[n-1].Commit))
	b.WriteString("| Operation | latest (ns/op) | previous (ns/op) | change |\n")
	b.WriteString("|---|--:|--:|--:|\n")
	for _, r := range flagged {
		fmt.Fprintf(&b, "| %s | %s | %s | +%.0f%% |\n",
			r.Label, formatNs(r.ToNs), formatNs(r.FromNs), r.PercentNs)
	}
	b.WriteString("\n")
	return b.String()
}

// detectRegressions returns the headlines that regressed in BOTH the most recent
// comparison (n-2 → n-1) and the one before it (n-3 → n-2). Callers guarantee at
// least three entries.
func detectRegressions(entries []HistoryEntry) []regression {
	n := len(entries)
	latestOld, latest := entries[n-2], entries[n-1]
	priorOld, prior := entries[n-3], entries[n-2]

	var flagged []regression
	for _, h := range headlines {
		key := sampleKey{h.Pkg, h.Impl, h.Op, h.Size}
		if !regressed(priorOld, prior, key) {
			continue
		}
		ok, from, to := regressedWithMedians(latestOld, latest, key)
		if !ok {
			continue
		}
		flagged = append(flagged, regression{
			Label: h.Label, FromNs: from, ToNs: to, PercentNs: (to/from - 1) * 100,
		})
	}
	return flagged
}

// regressed reports whether the benchmark cell key got significantly and
// materially slower from oldE to newE.
func regressed(oldE, newE HistoryEntry, key sampleKey) bool {
	ok, _, _ := regressedWithMedians(oldE, newE, key)
	return ok
}

// regressedWithMedians is regressed plus the old/new medians it compared, so the
// caller can report the magnitude. Returns ok=false (and zero medians) when the
// cell is missing on either side or the slowdown isn't both > threshold and
// statistically significant.
func regressedWithMedians(oldE, newE HistoryEntry, key sampleKey) (ok bool, from, to float64) {
	o, n := oldE.Samples[key], newE.Samples[key]
	if len(o) == 0 || len(n) == 0 {
		return false, 0, 0
	}
	mo, mn := median(o), median(n)
	if mo <= 0 || mn <= mo*(1+trendRegressFrac) {
		return false, 0, 0
	}
	if mannWhitneyP(o, n) >= trendPValue {
		return false, 0, 0
	}
	return true, mo, mn
}

// trendRecipe documents how to compare any two retained commits by hand. Static
// text: the snapshots are plain `go test` output, so benchstat consumes them
// with no preprocessing.
const trendRecipe = "### Compare any two commits manually\n\n" +
	"Each snapshot under `docs/bench/history/` is raw `go test -bench` output, so benchstat compares two " +
	"of them directly:\n\n" +
	"```sh\n" +
	"benchstat docs/bench/history/<older>_<sha>.txt docs/bench/history/<newer>_<sha>.txt\n" +
	"```\n\n" +
	"benchstat prints each benchmark's delta and `p`-value; trust a change only when `p` is low (a " +
	"non-`~` delta).\n\n"
